package docs

import (
	"fmt"
	"strings"
)

// Agents renders the model for AI agents: coding agents working in the
// app's repository, and operations agents setting deployment values. It
// puts the hard rules first, then one block of key: value lines per input,
// then the boot errors. It can be included in an AGENTS.md or served as
// an llms.txt-style file. It reads only the model.
func Agents(m *Model) []byte {
	var b strings.Builder
	name := m.Service.Name
	b.WriteString(header)
	fmt.Fprintf(&b, "\n# %s configuration: rules for agents\n\n", name)
	fmt.Fprintf(&b, "This file lists every configuration input %s reads, from its docuconf contract. It is for coding agents changing the app and for agents setting its deployment values. %s\n\n",
		code(name), "Generated by docuconf from the contract; do not edit it. To change an input, change the app's declaration, export the contract again, then run `docuconf docs`.")

	var vars, files, secrets, required, deprecated []string
	for _, g := range m.Groups {
		for _, in := range g.Inputs {
			if in.Kind == KindVar {
				vars = append(vars, in.Name)
			} else {
				files = append(files, in.Name)
			}
			if in.Secret {
				secrets = append(secrets, in.Name)
			}
			if in.Required && len(in.Default) == 0 {
				required = append(required, in.Name)
			}
			if in.Deprecated != nil {
				d := code(in.Name)
				if in.Deprecated.ReplacedBy != "" {
					d += " (use " + code(in.Deprecated.ReplacedBy) + ")"
				}
				deprecated = append(deprecated, d)
			}
		}
	}

	b.WriteString("## Hard rules\n\n")
	rules := []string{
		"Never put a secret value in code, a `.env` file, a values file, a ConfigMap, an annotation, a commit, a log or a message. Supply a secret variable only as a `secretKeyRef` or `injected`, and a secret file only from a `secret`, `certificate` or `csi` source or `injected`." +
			listOrNone(" Secret inputs: ", secrets, "."),
		"Use each input's declared wire format when writing a raw environment value (a `.env` file, a shell, `docker run -e`): list and duration formats differ between apps. In a platform values file, write typed values instead (lists as lists, durations in Go syntax such as `90s`); docuconf renders the wire format.",
		"Validate before proposing a change: `docuconf vet -contract contract.cue -values values.yaml -files files.yaml` for platform values, and `docuconf check -contract contract.cue` in a running environment. Both print every problem and exit 1.",
		"Do not invent inputs. " + code(name) + " reads only the " + countWords(len(vars), "environment variable", "environment variables") + " and " + countWords(len(files), "file", "files") + " below; `vet` rejects a value for anything else. A new input needs a change to the app's declaration and a new contract export.",
	}
	if len(required) > 0 {
		rules = append(rules, "Set every required input that has no default: "+join(required, "and")+".")
	}
	if len(deprecated) > 0 {
		rules = append(rules, "Do not add or use deprecated inputs: do not read them in new code, and do not set them in values or files; set their replacement instead. Deprecated: "+strings.Join(deprecated, ", ")+".")
	}
	for i, r := range rules {
		fmt.Fprintf(&b, "%d. %s\n", i+1, r)
	}

	g := m.Service.Generator
	b.WriteString("\n## Using this config in code\n\n")
	fmt.Fprintf(&b, "- The app declares these inputs in its own code with a docuconf SDK (this contract was exported by %s %s, %s). The contract and the docs are generated from that declaration: edit the declaration, never the generated files.\n",
		code(g.SDK), code(g.Version), g.Language)
	b.WriteString("- Read configuration through the SDK's typed values, not by reading environment variables or files directly: the SDK validates every input at boot and fails with all problems listed.\n")
	b.WriteString("- `config key` below is where a setting lives in the app's own configuration (its options class, settings file or config path). Search the code for it, or for the variable name, to find where it is read.\n")
	b.WriteString("- A file input is read from its `path`. For local runs, `DOCUCONF_FILE_ROOT=./dev` makes the SDK read every path under `./dev`.\n")
	b.WriteString("- Descriptions and details below are the app authors' own documentation of each input.\n")

	b.WriteString("\n## Setting values\n\n")
	for _, s := range []struct{ kind, title string }{{KindVar, "Environment variables"}, {KindFile, "Files"}} {
		first := true
		for _, gr := range m.Groups {
			for _, in := range gr.Inputs {
				if in.Kind != s.kind {
					continue
				}
				if first {
					fmt.Fprintf(&b, "### %s\n\n", s.title)
					first = false
				}
				agentInput(&b, m, in)
			}
		}
	}

	b.WriteString("### Source kinds\n\n")
	for _, s := range sourceKinds(m) {
		fmt.Fprintf(&b, "- %s: %s\n", code(s.Kind), s.Text)
	}
	b.WriteString("\n")

	if m.Profiles != nil {
		p := m.Profiles
		fmt.Fprintf(&b, "### Profiles\n\n- selector: %s\n- profiles: %s\n- default profile: %s\n- rule: a profile's defaults apply only when it is selected; platform values override them.\n\n",
			code(p.Selector), join(p.Names, "and"), code(p.Default))
	}
	if len(m.Overlays) > 0 {
		b.WriteString("### Config-file overlays\n\n")
		for _, o := range m.Overlays {
			fmt.Fprintf(&b, "- overlay %s: format %s, path %s, key separator %s, reload %s\n", code(o.Name), code(o.Format), code(o.Path), code(o.KeySeparator), code(o.Reload))
		}
		b.WriteString("- rule: a variable comes from the environment or one overlay, never both; secrets never go in an overlay.\n\n")
	}

	if len(m.Errors) > 0 {
		b.WriteString("## Boot errors\n\nAt boot the SDK reports every problem at once, one line each: `INPUT: message (code)`. Secret values never appear.\n\n")
		for _, e := range m.Errors {
			fmt.Fprintf(&b, "- %s: %s Fix: %s\n", code(e.Code), e.Meaning, e.Fix)
		}
	}
	return []byte(b.String())
}

func agentInput(b *strings.Builder, m *Model, in Input) {
	fmt.Fprintf(b, "#### %s\n\n", in.Name)
	line := func(k, v string) { fmt.Fprintf(b, "- %s: %s\n", k, oneLine(v)) }
	if in.Kind == KindVar {
		line("kind", "environment variable")
	} else {
		line("kind", "file")
	}
	line("type", typeText(in))
	if in.Group != "" {
		line("group", in.Group)
	}
	line("required", yesNo(in.Required))
	line("secret", yesNo(in.Secret))
	if d := in.Deprecated; d != nil {
		v := sentence(d.Message)
		if d.ReplacedBy != "" {
			v += " Use " + code(d.ReplacedBy) + " instead."
		}
		line("deprecated", v)
	}
	if f := in.File; f != nil {
		line("path", code(f.Path))
		if f.PathEnv != "" {
			line("path variable", code(f.PathEnv)+" (the platform sets it to the path)")
		}
		if f.Format != "" {
			line("format", code(f.Format))
		}
		line("contents", f.Contents)
		line("reload", code(f.Reload)+": "+f.ReloadText)
		if n := reloadNote(in); n != "" {
			line("reload note", n)
		}
	}
	if len(in.Default) > 0 {
		line("default", jsonValue(in.Default))
		line("default in the environment", envCode(in.DefaultEnv))
	} else if in.Kind == KindVar && !in.Required && !in.Secret {
		line("default", "none (unset unless the platform sets it)")
	}
	for _, p := range in.ProfileDefaults {
		line("default in profile "+code(p.Profile), jsonValue(p.Value))
	}
	if in.ProfileSelector && m.Profiles != nil {
		line("selects", "the profile; one of "+join(m.Profiles.Names, "or"))
	}
	for _, c := range in.Constraints {
		line("constraint", c.Text)
	}
	if w := in.Wire; w != nil {
		line("wire format", w.Text)
		line("in a values file", w.Platform)
	}
	if r := in.Rotation; r != nil {
		steps := make([]string, len(r.Steps))
		for i, s := range r.Steps {
			steps[i] = fmt.Sprintf("(%d) %s", i+1, s)
		}
		line("rotation", r.Text+" "+strings.Join(steps, " "))
	}
	if in.ConfigKey != "" {
		line("config key", code(in.ConfigKey))
	}
	for _, e := range in.Examples {
		line("example", exampleCode(e))
	}
	if len(in.Fields) > 0 {
		for _, f := range in.Fields {
			line("field "+agentFieldPath(f.Path), agentField(f))
		}
	} else if schema := schemaOf(in); schema != nil {
		line("schema", code(compact(schema)))
	}
	line("allowed sources", sourceList(in.Sources))
	line("boot errors", codeList(in.Errors))
	fmt.Fprintf(b, "\n%s\n\n", oneLine(in.Description))
	if in.Details != "" {
		md, _ := demote(in.Details, 4)
		b.WriteString(md + "\n\n")
	}
}

// agentFieldPath names a field, or the whole value.
func agentFieldPath(p string) string {
	if p == "" {
		return "(the whole value)"
	}
	return code(p)
}

// agentField writes a field table row on one line: its type, whether it
// is required, its default and constraints, then its description; or the
// raw schema of a subtree the table cannot express.
func agentField(f Field) string {
	if f.Schema != nil {
		s := "see schema " + code(compact(f.Schema))
		if f.Required {
			s = "required; " + s
		}
		return s
	}
	parts := []string{f.Type}
	if f.Required {
		parts = append(parts, "required")
	} else {
		parts = append(parts, "optional")
	}
	if len(f.Default) > 0 {
		parts = append(parts, "default "+jsonValue(f.Default))
	}
	if len(f.Enum) > 0 {
		vals := make([]string, len(f.Enum))
		for i, e := range f.Enum {
			vals[i] = jsonValue(e)
		}
		parts = append(parts, "one of "+joinPlain(vals, "or"))
	}
	for _, c := range f.Constraints {
		parts = append(parts, c.Text)
	}
	s := strings.Join(parts, ", ")
	if f.Description != "" {
		s += ". " + sentence(f.Description)
	}
	return s
}

// exampleCode keeps an example on one line: as is when it can be, else
// as a JSON string.
func exampleCode(e string) string {
	if strings.ContainsAny(e, "\n\r") || e != strings.TrimSpace(e) || e == "" {
		return code(string(raw(e)))
	}
	return code(e)
}

func listOrNone(prefix string, xs []string, suffix string) string {
	if len(xs) == 0 {
		return ""
	}
	return prefix + join(xs, "and") + suffix
}
