package docs

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
)

// Markdown renders the model as a reference for developers, such as
// CONFIG.md: a table of contents by group, one section per input, the
// files, and what each boot error means. It reads only the model.
func Markdown(m *Model) []byte {
	title := m.Service.Name + " configuration"
	// Two passes: the first finds every anchor, so that the second can
	// link forwards (to a deprecated input's replacement).
	var r *mdRenderer
	var body string
	var prev map[string]string
	for range 2 {
		r = &mdRenderer{m: m, slugs: slugger{}, anchors: map[string]string{}, prev: prev}
		r.slugs.slug(title)
		r.slugs.slug("Contents")
		body = r.body()
		prev = r.anchors
	}

	var b strings.Builder
	b.WriteString(header)
	fmt.Fprintf(&b, "\n# %s\n\n", text(title))
	b.WriteString(generatedBy(m))
	b.WriteString("\n\n")
	b.WriteString(summary(m))
	b.WriteString("\n\n## Contents\n\n")
	r.contents(&b)
	b.WriteString(body)
	return []byte(b.String())
}

func (r *mdRenderer) body() string {
	var b strings.Builder
	r.section(&b, KindVar, "Environment variables")
	r.section(&b, KindFile, "Files")
	if r.m.Profiles != nil {
		r.profiles(&b)
	}
	if len(r.m.Overlays) > 0 {
		r.overlays(&b)
	}
	r.sources(&b)
	if len(r.m.Errors) > 0 {
		r.errors(&b)
	}
	return b.String()
}

type mdRenderer struct {
	m       *Model
	slugs   slugger
	anchors map[string]string // by kind/name, and for sections by title
	prev    map[string]string // the anchors of the first pass
}

func key(kind, name string) string { return kind + "/" + name }

// generatedBy says where the document comes from, without a timestamp.
func generatedBy(m *Model) string {
	s := "Generated by docuconf from the configuration contract of " + code(m.Service.Name)
	if m.Service.AppVersion != "" {
		s += " " + code(m.Service.AppVersion)
	}
	g := m.Service.Generator
	s += fmt.Sprintf(", exported by %s %s (%s). Do not edit this file: change the app's declaration, export the contract again, then run `docuconf docs`.",
		code(g.SDK), code(g.Version), text(g.Language))
	return s
}

// summary counts the inputs.
func summary(m *Model) string {
	var vars, files, required, secrets int
	for _, g := range m.Groups {
		for _, in := range g.Inputs {
			if in.Kind == KindVar {
				vars++
			} else {
				files++
			}
			if in.Required {
				required++
			}
			if in.Secret {
				secrets++
			}
		}
	}
	return fmt.Sprintf("%s reads %s and %s. %s required, and %s secret.",
		code(m.Service.Name), countWords(vars, "environment variable", "environment variables"),
		countWords(files, "file", "files"), capitalize(isAre(required)), isAre(secrets))
}

func countWords(n int, one, many string) string {
	switch n {
	case 0:
		return "no " + many
	case 1:
		return "1 " + one
	}
	return fmt.Sprintf("%d %s", n, many)
}

func isAre(n int) string {
	switch n {
	case 0:
		return "none is"
	case 1:
		return "1 is"
	}
	return fmt.Sprintf("%d are", n)
}

// grouped returns the groups holding inputs of one kind, with only those
// inputs, and whether any of them is a named group.
func grouped(m *Model, kind string) ([]Group, bool) {
	var out []Group
	named := false
	for _, g := range m.Groups {
		var ins []Input
		for _, in := range g.Inputs {
			if in.Kind == kind {
				ins = append(ins, in)
			}
		}
		if len(ins) > 0 {
			out = append(out, Group{Name: g.Name, Title: g.Title, Inputs: ins})
			named = named || g.Name != ""
		}
	}
	return out, named
}

func (r *mdRenderer) contents(b *strings.Builder) {
	for _, s := range []struct{ kind, title string }{{KindVar, "Environment variables"}, {KindFile, "Files"}} {
		groups, named := grouped(r.m, s.kind)
		if len(groups) == 0 {
			continue
		}
		fmt.Fprintf(b, "**[%s](#%s)**\n\n", s.title, r.anchors[s.title])
		for _, g := range groups {
			indent := ""
			if named {
				fmt.Fprintf(b, "- [%s](#%s)\n", text(g.Title), r.anchors[key("group-"+s.kind, g.Name)])
				indent = "  "
			}
			for _, in := range g.Inputs {
				var notes []string
				if in.Required {
					notes = append(notes, "required")
				}
				if in.Secret {
					notes = append(notes, "secret")
				}
				if in.Deprecated != nil {
					notes = append(notes, "deprecated")
				}
				note := ""
				if len(notes) > 0 {
					note = " (" + strings.Join(notes, ", ") + ")"
				}
				fmt.Fprintf(b, "%s- [%s](#%s): %s%s\n", indent, code(in.Name), r.anchors[key(in.Kind, in.Name)], text(in.Description), note)
			}
		}
		b.WriteString("\n")
	}
	var more []string
	for _, t := range []string{"Profiles", "Config-file overlays", "Sources", "Boot errors"} {
		if a, ok := r.anchors[t]; ok {
			more = append(more, fmt.Sprintf("[%s](#%s)", t, a))
		}
	}
	if len(more) > 0 {
		fmt.Fprintf(b, "**Also:** %s\n\n", strings.Join(more, " · "))
	}
}

func (r *mdRenderer) section(b *strings.Builder, kind, title string) {
	groups, named := grouped(r.m, kind)
	if len(groups) == 0 {
		return
	}
	r.anchors[title] = r.slugs.slug(title)
	fmt.Fprintf(b, "## %s\n\n", title)
	if kind == KindFile {
		b.WriteString("The platform mounts each file at its path; the app reads it there. With `DOCUCONF_FILE_ROOT=./dev`, the SDK reads every path under `./dev` instead, for local runs.\n\n")
	}
	level := 3
	if named {
		level = 4
	}
	for _, g := range groups {
		if named {
			r.anchors[key("group-"+kind, g.Name)] = r.slugs.slug(g.Title)
			fmt.Fprintf(b, "### %s\n\n", text(g.Title))
		}
		for _, in := range g.Inputs {
			r.input(b, in, level)
		}
	}
}

func (r *mdRenderer) input(b *strings.Builder, in Input, level int) {
	r.anchors[key(in.Kind, in.Name)] = r.slugs.slug(in.Name)
	fmt.Fprintf(b, "%s %s\n\n%s\n\n", strings.Repeat("#", level), code(in.Name), text(in.Description))
	if d := in.Deprecated; d != nil {
		fmt.Fprintf(b, "> **Deprecated.** %s", text(sentence(d.Message)))
		if d.ReplacedBy != "" {
			fmt.Fprintf(b, " Use %s instead.", r.link(in.Kind, d.ReplacedBy))
		}
		b.WriteString("\n\n")
	}

	b.WriteString("| Property | Value |\n|---|---|\n")
	row := func(k, v string) { fmt.Fprintf(b, "| %s | %s |\n", k, cell(v)) }
	row("Type", typeText(in))
	row("Required", yesNo(in.Required))
	if in.Secret {
		row("Secret", "yes: never write its value in code, docs or a values file")
	} else {
		row("Secret", "no")
	}
	if f := in.File; f != nil {
		row("Path", code(f.Path))
		if f.PathEnv != "" {
			row("Path variable", code(f.PathEnv)+", which the platform sets to the path")
		}
		row("Contents", f.Contents)
		row("Reload", code(f.Reload)+": "+f.ReloadText)
	}
	switch {
	case len(in.Default) > 0:
		d := valueCode(in.Default)
		if !(len(in.DefaultEnv) == 1 && in.DefaultEnv[0].Value == plainValue(in.Default)) {
			d += "; in the environment: " + envCode(in.DefaultEnv)
		}
		row("Default", d)
	case in.Kind == KindVar && !in.Required && !in.Secret:
		row("Default", "none: unset unless the platform sets it")
	}
	for _, p := range in.ProfileDefaults {
		row("Default in profile "+code(p.Profile), valueCode(p.Value))
	}
	if in.ProfileSelector && r.m.Profiles != nil {
		row("Selects", "the profile: "+join(r.m.Profiles.Names, "or")+"; "+code(r.m.Profiles.Default)+" when unset")
	}
	if len(in.Constraints) > 0 {
		texts := make([]string, len(in.Constraints))
		for i, c := range in.Constraints {
			texts[i] = c.Text
		}
		row("Constraints", strings.Join(texts, "; "))
	}
	if w := in.Wire; w != nil {
		row("Wire format", w.Text)
		row("In a values file", w.Platform)
	}
	if in.ConfigKey != "" {
		row("Config key", code(in.ConfigKey))
	}
	row("Sources", sourceList(in.Sources))
	row("Boot errors", codeList(in.Errors))
	b.WriteString("\n")

	if r := in.Rotation; r != nil {
		fmt.Fprintf(b, "**Rotation.** %s\n\n", r.Text)
		for i, s := range r.Steps {
			fmt.Fprintf(b, "%d. %s\n", i+1, s)
		}
		b.WriteString("\n")
	}
	if len(in.Fields) > 0 {
		r.fields(b, in)
	} else if schema := schemaOf(in); schema != nil {
		schemaBlock(b, "JSON Schema", schema)
	}
	if len(in.Examples) > 0 {
		// Short examples in a list; long or multi-line ones in blocks.
		b.WriteString("Examples:\n")
		list := false
		for _, e := range in.Examples {
			if shortValue(e) {
				if !list {
					b.WriteString("\n")
					list = true
				}
				fmt.Fprintf(b, "- %s\n", code(e))
			} else {
				list = false
				b.WriteString("\n" + fence("text", e))
			}
		}
		b.WriteString("\n")
	}
	if in.Details != "" {
		md, heads := demote(in.Details, level)
		for _, h := range heads {
			r.slugs.slug(h)
		}
		b.WriteString(md + "\n\n")
	}
}

// fields renders a JSON Schema's field table, then the raw schema of each
// subtree the table could not express (SPEC §14.3).
func (r *mdRenderer) fields(b *strings.Builder, in Input) {
	what := "Fields of the value"
	if in.Kind == KindFile {
		what = "Fields of the file"
	}
	fmt.Fprintf(b, "%s, from its JSON Schema:\n\n", what)
	b.WriteString("| Field | Type | Required | Default | Constraints | Description |\n|---|---|---|---|---|---|\n")
	for _, f := range in.Fields {
		var cons []string
		if len(f.Enum) > 0 {
			vals := make([]string, len(f.Enum))
			for i, e := range f.Enum {
				vals[i] = valueCode(e)
			}
			cons = append(cons, "one of "+joinPlain(vals, "or"))
		}
		for _, c := range f.Constraints {
			cons = append(cons, c.Text)
		}
		def := ""
		if len(f.Default) > 0 {
			def = valueCode(f.Default)
		}
		typ := f.Type
		if f.Schema != nil {
			typ = "see the schema below"
		}
		fmt.Fprintf(b, "| %s | %s | %s | %s | %s | %s |\n", fieldPath(f.Path), cell(typ), yesNo(f.Required), cell(def),
			cell(strings.Join(cons, "; ")), cell(text(f.Description)))
	}
	b.WriteString("\n")
	for _, f := range in.Fields {
		if f.Schema != nil {
			title := "JSON Schema"
			if f.Path != "" {
				title += " of " + code(f.Path)
			}
			schemaBlock(b, title, f.Schema)
		}
	}
}

// fieldPath shows a field's path as code, or says it is the whole value.
func fieldPath(p string) string {
	if p == "" {
		return "(the whole value)"
	}
	return cell(code(p))
}

// schemaBlock writes a JSON Schema, indented, in a collapsed block.
func schemaBlock(b *strings.Builder, title string, schema json.RawMessage) {
	var pretty bytes.Buffer
	json.Indent(&pretty, []byte(compact(schema)), "", "  ")
	fmt.Fprintf(b, "<details>\n<summary>%s</summary>\n\n%s\n</details>\n\n", title, fence("json", pretty.String()))
}

// joinPlain joins phrases: a, b or c.
func joinPlain(xs []string, last string) string {
	if len(xs) < 2 {
		return strings.Join(xs, "")
	}
	return strings.Join(xs[:len(xs)-1], ", ") + " " + last + " " + xs[len(xs)-1]
}

// link points at another input when the model has it.
func (r *mdRenderer) link(kind, name string) string {
	if a, ok := r.prev[key(kind, name)]; ok {
		return fmt.Sprintf("[%s](#%s)", code(name), a)
	}
	return code(name)
}

func (r *mdRenderer) profiles(b *strings.Builder) {
	p := r.m.Profiles
	r.anchors["Profiles"] = r.slugs.slug("Profiles")
	fmt.Fprintf(b, "## Profiles\n\n%s selects which of the app's profile files load: %s. When it is unset, the profile is %s. A profile's defaults apply only when it is selected, and the platform's values override them.\n\n",
		code(p.Selector), join(p.Names, "or"), code(p.Default))
}

func (r *mdRenderer) overlays(b *strings.Builder) {
	r.anchors["Config-file overlays"] = r.slugs.slug("Config-file overlays")
	b.WriteString("## Config-file overlays\n\nThe platform may write a variable with a config key into one of these files instead of the environment. It loads after the app's own config files and before environment variables.\n\n")
	b.WriteString("| Overlay | Format | Path | Key separator | Reload |\n|---|---|---|---|---|\n")
	for _, o := range r.m.Overlays {
		fmt.Fprintf(b, "| %s | %s | %s | %s | %s |\n", code(o.Name), code(o.Format), cell(code(o.Path)), cell(code(o.KeySeparator)), code(o.Reload))
	}
	b.WriteString("\n")
}

func (r *mdRenderer) sources(b *strings.Builder) {
	r.anchors["Sources"] = r.slugs.slug("Sources")
	b.WriteString("## Sources\n\nWhere the platform may get each input from, as named in the tables above. A secret comes only from a secret store or an injector.\n\n")
	for _, s := range sourceKinds(r.m) {
		fmt.Fprintf(b, "- %s: %s\n", code(s.Kind), s.Text)
	}
	b.WriteString("\n")
}

func (r *mdRenderer) errors(b *strings.Builder) {
	r.anchors["Boot errors"] = r.slugs.slug("Boot errors")
	b.WriteString("## Boot errors\n\nAt boot the SDK checks every input and reports all problems together, one line each, with one of these codes. Secret values never appear in the messages.\n\n")
	b.WriteString("| Code | Meaning | Fix |\n|---|---|---|\n")
	for _, e := range r.m.Errors {
		fmt.Fprintf(b, "| %s | %s | %s |\n", code(e.Code), cell(e.Meaning), cell(e.Fix))
	}
}

func capitalize(s string) string { return strings.ToUpper(s[:1]) + s[1:] }

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

func mapStrings(xs []string, f func(string) string) []string {
	out := make([]string, len(xs))
	for i, x := range xs {
		out[i] = f(x)
	}
	return out
}
