package docs

import (
	"bytes"
	"encoding/json"
	"regexp"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

// Markdown helpers shared by the renderers.

// header is the first line of every rendered file.
const header = "<!-- Generated by docuconf. Do not edit. -->\n"

// oneLine collapses whitespace, so a description can sit in a table cell
// or a list item.
func oneLine(s string) string { return strings.Join(strings.Fields(s), " ") }

var mdSpecial = strings.NewReplacer(
	`\`, `\\`, "`", "\\`", "*", `\*`, "_", `\_`, "[", `\[`, "]", `\]`,
	"<", `\<`, ">", `\>`, "|", `\|`,
)

// text escapes plain text (a description) for Markdown: descriptions are
// plain text, details are Markdown (SPEC §14.4).
func text(s string) string {
	s = mdSpecial.Replace(oneLine(s))
	// Characters that start a block at the beginning of a line.
	if s != "" && strings.ContainsRune("#+-=", rune(s[0])) {
		s = `\` + s
	}
	if m := orderedListRe.FindStringIndex(s); m != nil {
		s = s[:m[1]-1] + `\` + s[m[1]-1:]
	}
	return s
}

var orderedListRe = regexp.MustCompile(`^[0-9]{1,9}[.)]`)

// cell makes inline Markdown safe in a GFM table cell: pipes are escaped,
// even inside code spans, and the cell is one line.
func cell(s string) string {
	return strings.ReplaceAll(oneLine(s), "|", `\|`)
}

// shortValue reports whether a value fits in a code span on one line.
func shortValue(s string) bool {
	return utf8.RuneCountInString(s) <= 60 && !strings.ContainsAny(s, "\n\r") && s == strings.TrimSpace(s) && s != ""
}

// valueCode shows a typed value: a short, plain string as is, anything
// else as compact JSON.
func valueCode(v json.RawMessage) string { return code(plainValue(v)) }

// plainValue is the text valueCode shows.
func plainValue(v json.RawMessage) string {
	var s string
	if json.Unmarshal(v, &s) == nil && shortValue(s) {
		return s
	}
	return compact(v)
}

// jsonValue shows a typed value as JSON, which is also YAML, for a
// platform values file.
func jsonValue(v json.RawMessage) string { return code(compact(v)) }

// compact writes a JSON value on one line, however the model was indented.
func compact(v json.RawMessage) string {
	var buf bytes.Buffer
	if json.Compact(&buf, v) != nil {
		return string(v)
	}
	return buf.String()
}

// sourceList names an input's sources, with what is particular to it.
func sourceList(srcs []Source) string {
	parts := make([]string, len(srcs))
	for i, s := range srcs {
		parts[i] = code(s.Kind)
		if s.Note != "" {
			parts[i] += " (" + s.Note + ")"
		}
	}
	return strings.Join(parts, ", ")
}

// sourceKinds returns each source kind the model uses, with its text, in
// order of first use.
func sourceKinds(m *Model) []Source {
	var out []Source
	seen := map[string]bool{}
	for _, g := range m.Groups {
		for _, in := range g.Inputs {
			for _, s := range in.Sources {
				if !seen[s.Kind] {
					seen[s.Kind] = true
					out = append(out, Source{Kind: s.Kind, Text: s.Text})
				}
			}
		}
	}
	return out
}

// schemaOf returns the JSON Schema of an input's schema constraint.
func schemaOf(in Input) json.RawMessage {
	for _, c := range in.Constraints {
		if c.Rule == "schema" {
			return c.Params["schema"]
		}
	}
	return nil
}

// typeText shows an input's type and, when it says more, its label.
func typeText(in Input) string {
	if in.TypeLabel == in.Type {
		return code(in.Type)
	}
	return code(in.Type) + " (" + in.TypeLabel + ")"
}

// sentence ends s with a period unless it already ends a sentence.
func sentence(s string) string {
	s = oneLine(s)
	if s == "" || strings.ContainsAny(s[len(s)-1:], ".!?") {
		return s
	}
	return s + "."
}

// codeList joins codes as code spans, or says none.
func codeList(xs []string) string {
	if len(xs) == 0 {
		return "none"
	}
	return strings.Join(mapStrings(xs, code), ", ")
}

// envCode shows the environment entries of a default.
func envCode(env []EnvEntry) string {
	parts := make([]string, len(env))
	for i, e := range env {
		v := e.Value
		if strings.ContainsAny(v, "\n\r") {
			v = strconv.Quote(v)
		}
		parts[i] = code(e.Name + "=" + v)
	}
	return strings.Join(parts, " ")
}

var backticksRe = regexp.MustCompile("`+")

// fence writes a fenced code block with a fence longer than any run of
// backticks in s.
func fence(lang, s string) string {
	n := 3
	for _, run := range backticksRe.FindAllString(s, -1) {
		n = max(n, len(run)+1)
	}
	f := strings.Repeat("`", n)
	return f + lang + "\n" + strings.TrimRight(s, "\n") + "\n" + f + "\n"
}

// ----- headings -----

var (
	atxRe     = regexp.MustCompile(`^( {0,3})(#{1,6})([ \t]+|$)(.*)$`)
	setextRe  = regexp.MustCompile(`^ {0,3}(=+|-+)[ \t]*$`)
	fenceRe   = regexp.MustCompile("^ {0,3}(`{3,}|~{3,})")
	blockRe   = regexp.MustCompile(`^ {0,3}([-+*>|]|[0-9]{1,9}[.)]|#|$)`)
	closingRe = regexp.MustCompile(`[ \t]+#+[ \t]*$`)
)

// demote rewrites the details of an input so that its headings nest under
// the input's own heading, at level base: a level-n heading becomes level
// base+n, at most 6. Setext headings become ATX headings. Lines inside
// fenced code blocks are left alone. It returns the rewritten Markdown
// and the text of each heading, in order.
func demote(md string, base int) (string, []string) {
	lines := strings.Split(md, "\n")
	var out []string
	var heads []string
	var inFence string
	prevPara := false // the previous line is paragraph text
	for i := 0; i < len(lines); i++ {
		l := lines[i]
		if inFence != "" {
			out = append(out, l)
			if m := fenceRe.FindStringSubmatch(l); m != nil && m[1][0] == inFence[0] && len(m[1]) >= len(inFence) && strings.TrimSpace(l) == m[1] {
				inFence = ""
			}
			continue
		}
		if m := fenceRe.FindStringSubmatch(l); m != nil {
			inFence = m[1]
			out = append(out, l)
			prevPara = false
			continue
		}
		if m := atxRe.FindStringSubmatch(l); m != nil {
			title := strings.TrimSpace(closingRe.ReplaceAllString(m[4], ""))
			out = append(out, heading(base+len(m[2]), title))
			heads = append(heads, title)
			prevPara = false
			continue
		}
		if m := setextRe.FindStringSubmatch(l); m != nil && prevPara {
			level := 2
			if m[1][0] == '=' {
				level = 1
			}
			title := strings.TrimSpace(out[len(out)-1])
			out[len(out)-1] = heading(base+level, title)
			heads = append(heads, title)
			prevPara = false
			continue
		}
		prevPara = !blockRe.MatchString(l) && !strings.HasPrefix(l, "    ") && !strings.HasPrefix(l, "\t")
		out = append(out, l)
	}
	return strings.Join(out, "\n"), heads
}

func heading(level int, title string) string {
	return strings.Repeat("#", min(level, 6)) + " " + title
}

// slugger makes GitHub-style heading anchors, unique in one document.
type slugger map[string]int

var slugDrop = regexp.MustCompile("[`*~]")

func (s slugger) slug(title string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(slugDrop.ReplaceAllString(title, "")) {
		switch {
		case r == ' ':
			b.WriteRune('-')
		case r == '-' || r == '_' || unicode.IsLetter(r) || unicode.IsNumber(r):
			b.WriteRune(r)
		}
	}
	base := b.String()
	n, seen := s[base]
	s[base] = n + 1
	if !seen {
		return base
	}
	slug := base + "-" + strconv.Itoa(n)
	s[slug]++
	return slug
}
