// Code generated by docuconf. DO NOT EDIT.
// This is what a language SDK emits for one service.
package examples

import "docuconf.dev/contract"

billing: contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name:       "billing-api"
		appVersion: "1.4.0"
		generator: {language: "ruby", sdk: "docuconf-rails", version: "0.1.0"}
	}
	vars: {
		DATABASE_URL: {
			type:        "url"
			description: "Primary Postgres connection string"
			required:    true
			secret:      true
			schemes: ["postgres", "postgresql"]
		}
		PORT: {
			type:        "int"
			description: "HTTP listen port"
			default:     8080
			min:         1
			max:         65535
		}
		LOG_LEVEL: {
			type:        "enum"
			description: "Minimum log level emitted"
			values: ["debug", "info", "warn", "error"]
			default: "info"
		}
		REQUEST_TIMEOUT: {
			type:        "duration"
			description: "Upstream request timeout"
			default:     "30s"
			min:         "1s"
			max:         "5m"
		}
		ALLOWED_ORIGINS: {
			type:        "list"
			description: "CORS origins allowed to call the API"
			items:       "string"
			required:    true
			minItems:    1
		}
		STRIPE_API_BASE: {
			type:        "url"
			description: "Stripe API base URL"
			schemes: ["https"]
			default: "https://api.stripe.com"
		}
	}
}
