// Code generated by docuconf. DO NOT EDIT.
// A .NET service that layers a platform-mounted appsettings file between
// its baked-in appsettings*.json and environment variables:
//
//	builder.Configuration.AddJsonFile("appsettings.json", optional: false);
//	builder.Configuration.AddJsonFile("/app/config/appsettings.Production.json", optional: true, reloadOnChange: true);
//	builder.Configuration.AddEnvironmentVariables();
package examples

import "docuconf.dev/contract"

catalog: contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "catalog-api"
		generator: {language: "dotnet", sdk: "Docuconf.Options", version: "0.2.0"}
	}
	vars: {
		CATALOG__CACHETTL: {
			type:        "duration"
			description: "How long catalog pages are cached"
			encoding:    "timespan"
			default:     "5m"
			max:         "1h"
			configKey:   "Catalog:CacheTtl"
		}
		CATALOG__DBPASSWORD: {
			type:        "string"
			description: "Catalog database password"
			required:    true
			secret:      true
			configKey:   "Catalog:DbPassword"
		}
		CATALOG__FEATUREDCATEGORIES: {
			type:        "list"
			description: "Categories shown on the home page"
			items:       "string"
			encoding:    "indexed"
			maxItems:    10
			configKey:   "Catalog:FeaturedCategories"
		}
		CATALOG__PAGESIZE: {
			type:        "int"
			description: "Items per page"
			default:     20
			min:         1
			max:         500
			configKey:   "Catalog:PageSize"
		}
		CATALOG__SEARCH__URL: {
			type:        "url"
			description: "Search service endpoint"
			required:    true
			schemes: ["https"]
			configKey: "Catalog:Search:Url"
		}
		CATALOG__TRACEHEADER: {
			type:        "string"
			description: "Header carrying the trace id"
			default:     "traceparent"
		}
		LOGGING__LOGLEVEL__DEFAULT: {
			type:        "enum"
			description: "Minimum log level"
			values: ["Trace", "Debug", "Information", "Warning", "Error"]
			default:   "Information"
			configKey: "Logging:LogLevel:Default"
		}
	}
	overlays: platform: {
		description:  "Platform overrides, layered over the baked-in appsettings files"
		format:       "json"
		path:         "/app/config/appsettings.Production.json"
		keySeparator: ":"
		reload:       "watch"
	}
}
