// Code generated by docuconf. DO NOT EDIT.
// An API gateway that reads every kind of input: env vars of each
// source, a structured config file, a TLS key pair, a CA bundle, a
// keystore, a licence file and a large binary database.
package examples

import "docuconf.dev/contract"

gateway: contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "gateway"
		generator: {language: "go", sdk: "docuconf-go", version: "0.1.0"}
	}
	vars: {
		LOG_LEVEL: {
			type:        "enum"
			description: "Minimum log level emitted"
			values: ["debug", "info", "warn", "error"]
			default: "info"
		}
		POD_NAMESPACE: {
			type:        "string"
			description: "Namespace the gateway runs in, for metrics labels"
			required:    true
		}
		GOMEMLIMIT: {
			type:        "int"
			description: "Go runtime soft memory limit, in bytes"
			min:         1
		}
		RATE_LIMITS: {
			type:        "json"
			description: "Default per-client rate limits"
			// Generated from the app's RateLimits type.
			schema: {
				type: "object"
				required: ["perMinute"]
				additionalProperties: false
				properties: {
					perMinute: {type: "integer", minimum: 1}
					burst: {type: "integer", minimum: 0}
				}
			}
		}
		PARTNER_KEYSTORE_PASSWORD: {
			type:        "string"
			description: "Password for the partner mTLS keystore"
			required:    true
			secret:      true
		}
	}
	files: {
		routes: {
			type:        "config"
			format:      "yaml"
			description: "Routing table: path prefixes and their upstreams"
			required:    true
			path:        "/etc/gateway/routes/routes.yaml"
			pathEnv:     "ROUTES_FILE"
			reload:      "watch"
			maxSize:     65536
			// Generated from the app's Routes type.
			schema: {
				type: "object"
				required: ["routes"]
				additionalProperties: false
				properties: routes: {
					type:     "array"
					minItems: 1
					items: {
						type: "object"
						required: ["match", "upstream"]
						additionalProperties: false
						properties: {
							match: {type: "string", pattern: "^/"}
							upstream: {type: "string", pattern: "^https?://"}
							timeout: {type: "string", pattern: "^([0-9]+(ms|s|m))+$"}
						}
					}
				}
			}
		}
		"serving-tls": {
			type:        "tls"
			description: "Certificate the gateway serves HTTPS with"
			required:    true
			path:        "/etc/gateway/tls"
			reload:      "watch"
			dnsNames: ["gateway.internal", "api.example.com"]
			keyAlgorithms: ["ECDSA", "RSA"]
			minRemaining: "720h"
		}
		"upstream-ca": {
			type:        "caBundle"
			description: "Private CAs the gateway trusts for upstream TLS"
			path:        "/etc/gateway/ca/bundle.pem"
			pathEnv:     "SSL_CERT_FILE"
		}
		"partner-keystore": {
			type:        "keystore"
			format:      "pkcs12"
			description: "Client certificate for mTLS to the partner API"
			path:        "/etc/gateway/partner/keystore.p12"
			passwordVar: "PARTNER_KEYSTORE_PASSWORD"
		}
		license: {
			type:        "text"
			description: "Gateway licence key"
			required:    true
			path:        "/etc/gateway/license/license.key"
			pattern:     "^[A-Z0-9]{5}(-[A-Z0-9]{5}){3}\\n?$"
		}
		geoip: {
			type:        "binary"
			description: "GeoIP database for country-based routing"
			path:        "/data/geoip/GeoLite2-City.mmdb"
			maxSize:     134217728
		}
	}
}
