// Code generated by docuconf. DO NOT EDIT.
// A .NET service configured mostly through appsettings files. The
// exporter read these from the build output:
//
//   appsettings.json             {"Inventory": {"Port": 8080}}
//   appsettings.Production.json  {"Inventory": {"WarehouseApi": "https://warehouse.internal"}}
//   appsettings.Staging.json     {"Inventory": {"WarehouseApi": "https://warehouse.staging.internal"}}
//
// Port has a value in the base file, so it is an ordinary default.
// WarehouseApi is [Required] and only set per environment, so it stays
// required, and the selected profile can satisfy it.
package examples

import "docuconf.dev/contract"

inventory: contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "inventory-api"
		generator: {language: "dotnet", sdk: "Docuconf.Options", version: "0.1.0"}
	}
	vars: {
		DOTNET_ENVIRONMENT: {
			type:        "string"
			description: "Hosting environment; selects appsettings.{Environment}.json"
			default:     "Production"
		}
		INVENTORY__PORT: {
			type:        "int"
			description: "HTTP listen port"
			configKey:   "Inventory:Port"
			default:     8080
			min:         1
			max:         65535
		}
		INVENTORY__WAREHOUSEAPI: {
			type:        "url"
			description: "Base URL of the warehouse service"
			configKey:   "Inventory:WarehouseApi"
			required:    true
			schemes: ["https"]
		}
		INVENTORY__DBPASSWORD: {
			type:        "string"
			description: "Database password"
			configKey:   "Inventory:DbPassword"
			required:    true
			secret:      true
		}
	}
	profiles: {
		selector: "DOTNET_ENVIRONMENT"
		default:  "Production"
		defaults: {
			Production: INVENTORY__WAREHOUSEAPI: "https://warehouse.internal"
			Staging: INVENTORY__WAREHOUSEAPI:    "https://warehouse.staging.internal"
		}
	}
}

// Production (the default): appsettings.Production.json supplies the
// warehouse URL, so the platform only provides the secret.
inventoryProd: contract.#Validate & {contract: inventory, values: {
	INVENTORY__DBPASSWORD: secretKeyRef: {name: "inventory-db", key: "password"}
}}

// Staging, with an env override of the profile's value. Env vars win
// over appsettings files in .NET's default configuration order.
inventoryStaging: contract.#Validate & {contract: inventory, values: {
	DOTNET_ENVIRONMENT:      "Staging"
	INVENTORY__WAREHOUSEAPI: "https://warehouse-canary.staging.internal"
	INVENTORY__DBPASSWORD: secretKeyRef: {name: "inventory-db", key: "password"}
}}
