// Code generated by docuconf. DO NOT EDIT.
// A service whose secrets and telemetry settings are supplied by injectors
// in some clusters (injector_pod.cue). The contract names none of them: it
// only says what the app reads.
package examples

import "docuconf.dev/contract"

ledger: contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name:       "ledger-api"
		appVersion: "3.1.0"
		generator: {language: "go", sdk: "docuconf-go", version: "0.1.0"}
	}
	vars: {
		LOG_LEVEL: {
			type:        "enum"
			description: "Minimum log level emitted"
			values: ["debug", "info", "warn", "error"]
			default: "info"
		}
		DB_PASSWORD: {
			type:        "string"
			description: "Password for the ledger database user"
			secret:      true
		}
		OTEL_EXPORTER_OTLP_ENDPOINT: {
			type:        "url"
			description: "OTLP collector the app sends traces to"
		}
		AZURE_CLIENT_ID: {
			type:        "string"
			description: "Client ID of the managed identity the app signs in as"
		}
	}
	files: "db-creds": {
		type:        "config"
		format:      "json"
		description: "Database credentials, as {\"username\": ..., \"password\": ...}"
		secret:      true
		path:        "/vault/secrets/db.json"
		pathEnv:     "DB_CREDS_FILE"
		schema: {
			type: "object"
			required: ["username", "password"]
			properties: {
				username: type: "string"
				password: type: "string"
			}
		}
	}
}
