// Code generated by docuconf. DO NOT EDIT.
// A .NET service: Microsoft.Extensions.Configuration binds lists from
// indexed keys and TimeSpan from hh:mm:ss, so the contract says so.
package examples

import "docuconf.dev/contract"

orders: contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "orders-api"
		generator: {language: "dotnet", sdk: "Docuconf.Options", version: "0.1.0"}
	}
	vars: {
		ORDERS__BROKERS: {
			type:        "list"
			description: "Kafka bootstrap servers"
			items:       "string"
			encoding:    "indexed"
			required:    true
			minItems:    1
		}
		ORDERS__PARTITIONS: {
			type:        "list"
			description: "Partitions this instance consumes"
			items:       "int"
			encoding:    "indexed"
			// The app reads them into int[], a 32-bit item type.
			itemMin: -2147483648
			itemMax: 2147483647
		}
		ORDERS__CHECKOUTTIMEOUT: {
			type:        "duration"
			description: "Time allowed to complete checkout"
			encoding:    "timespan"
			default:     "15m"
		}
	}
}

ordersEnv: (contract.#Render & {contract: orders, values: {
	ORDERS__BROKERS: ["kafka-0:9092", "kafka-1:9092"]
	ORDERS__CHECKOUTTIMEOUT: "26h3m4s500ms"
}}).env
