// Code generated by docuconf. DO NOT EDIT.
// A Python service: pydantic-settings decodes lists as JSON and
// timedelta from ISO 8601.
package examples

import "docuconf.dev/contract"

reports: contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "reports-worker"
		generator: {language: "python", sdk: "docuconf-pydantic", version: "0.1.0"}
	}
	vars: {
		REPORT_FORMATS: {
			type:        "list"
			description: "Formats the worker renders"
			items:       "string"
			encoding:    "json"
			default: ["pdf"]
		}
		POLL_INTERVAL: {
			type:        "duration"
			description: "How often to poll the job queue"
			encoding:    "iso8601"
			default:     "30s"
		}
	}
}

reportsEnv: (contract.#Render & {contract: reports, values: {
	REPORT_FORMATS: ["pdf", "csv"]
	POLL_INTERVAL: "1m30s"
}}).env
