// Code generated by docuconf. DO NOT EDIT.
// A contract that exercises generated docs (SPEC §14): details with
// Markdown headings, an input with no group next to grouped ones, a
// deprecated input with a replacement, an indexed list, secret files, a
// very long example, non-ASCII text and a key set.
package examples

import "docuconf.dev/contract"

storefront: contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name:       "storefront"
		appVersion: "2.3.0"
		generator: {language: "dotnet", sdk: "Docuconf.Options", version: "0.2.0"}
	}
	vars: {
		STOREFRONT__PORT: {
			type:        "int"
			description: "HTTP listen port"
			default:     8080
			min:         1
			max:         65535
			configKey:   "Storefront:Port"
		}
		STOREFRONT__GREETING: {
			type:        "string"
			description: "Begrüßung auf der Startseite (non-ASCII: «ça va», 東京)"
			group:       "ui"
			default:     "Grüß Gott!"
			minLength:   1
			maxLength:   120
			examples: ["Willkommen 👋", "いらっしゃいませ"]
			configKey: "Storefront:Greeting"
		}
		STOREFRONT__THEME: {
			type:        "enum"
			description: "Colour theme of the storefront"
			group:       "ui"
			values: ["light", "dark", "high-contrast"]
			default: "light"
		}
		STOREFRONT__BANNER: {
			type:        "string"
			description: "Banner text; superseded by the CMS"
			group:       "ui"
			deprecated: {
				message:    "Banners are managed in the CMS now"
				replacedBy: "STOREFRONT__CMS__URL"
			}
		}
		STOREFRONT__CMS__URL: {
			type:        "url"
			description: "Base URL of the content management system"
			group:       "ui"
			schemes: ["https", "http"]
			examples: ["https://cms.example.com/api/v2/spaces/storefront/environments/production/entries?content_type=banner&locale=de-AT&include=10&limit=1000&order=-sys.updatedAt"]
			details: """
				The CMS serves banners, landing pages and legal texts.

				# When to change it

				Point it at the staging CMS in staging. Setext headings are demoted too:

				Caveats
				-------

				```sh
				# a comment in a fenced block is not a heading
				curl "$STOREFRONT__CMS__URL/health"
				```
				"""
		}
		STOREFRONT__CACHE__TTL: {
			type:        "duration"
			description: "How long rendered pages are cached"
			group:       "performance"
			encoding:    "timespan"
			default:     "90s"
			min:         "1s"
			max:         "1h"
			configKey:   "Storefront:Cache:Ttl"
			details: """
				Pages are rendered from the CMS, so a longer TTL means fewer CMS calls
				and staler content. Raise it during sales, when traffic peaks.
				"""
		}
		STOREFRONT__SHARDS: {
			type:        "list"
			description: "Search shards this instance queries"
			group:       "performance"
			items:       "int"
			encoding:    "indexed"
			minItems:    1
			maxItems:    16
			itemMin:     0
			itemMax:     1023
			default: [0, 1]
			configKey: "Storefront:Shards"
		}
		STOREFRONT__LOCALES: {
			type:        "list"
			description: "Locales offered in the language picker"
			group:       "ui"
			items:       "string"
			encoding:    "csv"
			separator:   ";"
			default: ["de-AT", "en-GB"]
		}
		STOREFRONT__SAMPLE_RATE: {
			type:        "float"
			description: "Fraction of requests traced"
			group:       "observability"
			default:     0.1
			min:         0
			max:         1
		}
		STOREFRONT__DEBUG: {
			type:        "bool"
			description: "Log every request and response body"
			group:       "observability"
			default:     false
		}
		STOREFRONT__SKU_PATTERN: {
			type:        "string"
			description: "Pattern every product SKU must contain"
			pattern:     "[A-Z]{3}-[0-9]{4}"
			default:     "SKU-0000"
		}
		STOREFRONT__REQUEST_ID: {
			type:        "string"
			description: "Header that carries the request id"
			group:       "" // the same as no group
			pattern:     "^[A-Za-z-]+$"
			default:     "X-Request-Id"
		}
		STOREFRONT__RATE_LIMITS: {
			type:        "json"
			description: "Per-client rate limits"
			group:       "performance"
			default: {perMinute: 600}
			schema: {
				type: "object"
				required: ["perMinute"]
				additionalProperties: false
				properties: perMinute: {type: "integer", minimum: 1}
			}
		}
		STOREFRONT__PAYMENTS__WEBHOOKKEYS: {
			type:         "keySet"
			description:  "Keys that verify the signature on incoming payment webhooks"
			group:        "security"
			secret:       true
			keyMinLength: 32
			keyMaxLength: 256
		}
		STOREFRONT__DB__PASSWORD: {
			type:        "string"
			description: "Password of the storefront database user"
			group:       "database"
			required:    true
			secret:      true
			minLength:   16
		}
	}
	files: {
		"signing-key": {
			type:        "text"
			description: "Key that signs basket cookies"
			group:       "security"
			required:    true
			secret:      true
			path:        "/etc/storefront/signing/key.pem"
			pathEnv:     "STOREFRONT_SIGNING_KEY_FILE"
			maxSize:     4096
			pattern:     "^-----BEGIN PRIVATE KEY-----"
			details: """
				Rotate it by adding the new key to the Secret and rolling the pods;
				baskets signed with the old key are emptied.
				"""
		}
		catalogue: {
			type:        "config"
			format:      "json"
			description: "Product categories shown in the navigation"
			path:        "/etc/storefront/catalogue/catalogue.json"
			reload:      "watch"
			schema: {
				type: "object"
				required: ["categories"]
				properties: categories: {type: "array", items: {type: "string"}}
			}
		}
	}
}
