#!/usr/bin/env bash
# Writes the generated docs of every example contract (SPEC §14) into
# testdata/docs/<name>/: docs.json (the docs model), CONFIG.md (Markdown
# for developers) and CONFIG.agents.md (for agents). They are generated by
# docuconf docs and never edited by hand.
#
#   generate.sh          regenerate them
#   generate.sh --check  fail, with a diff, if any is out of date (CI)
#
# --check also renders the committed docs.json, to show that the
# renderers need nothing but the model. DOCUCONF names the CLI binary.
set -euo pipefail
cd "$(dirname "$0")/../../examples"
DOCUCONF="${DOCUCONF:-docuconf}"
mode=-o
if [ "${1:-}" = --check ]; then
  mode=--check
fi

for contract in *_contract.cue; do
  out="../testdata/docs/$(basename "$contract" _contract.cue)"
  mkdir -p "$out"
  "$DOCUCONF" docs "$contract" --format model "$mode" "$out/docs.json"
  "$DOCUCONF" docs "$contract" --format markdown "$mode" "$out/CONFIG.md"
  "$DOCUCONF" docs "$contract" --format agents "$mode" "$out/CONFIG.agents.md"
  if [ "$mode" = --check ]; then
    "$DOCUCONF" docs "$out/docs.json" --format markdown --check "$out/CONFIG.md"
    "$DOCUCONF" docs "$out/docs.json" --format agents --check "$out/CONFIG.agents.md"
  fi
done
