// Code generated by docuconf. DO NOT EDIT.
package orders

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name:       "orders-api"
		appVersion: "2.3.0"
		generator: {
			language: "go"
			sdk:      "docuconf-go"
			version:  "0.1.0"
		}
	}
	vars: {
		DATABASE_URL: {
			type:        "url"
			description: "Primary Postgres connection string"
			required:    true
			secret:      true
			schemes: ["postgres", "postgresql"]
		}
		KAFKA_BROKERS: {
			type:        "list"
			description: "Kafka brokers orders are published to"
			required:    true
			items:       "string"
			encoding:    "csv"
			separator:   ","
			minItems:    1
		}
		LOG_LEVEL: {
			type:        "enum"
			description: "Minimum log level emitted"
			default:     "info"
			values: ["debug", "info", "warn", "error"]
		}
		PAYMENTS_TIMEOUT: {
			type:        "duration"
			description: "Timeout for calls to the payments service"
			default:     "5s"
			min:         "100ms"
			max:         "30s"
			encoding:    "go"
		}
		PORT: {
			type:        "int"
			description: "HTTP listen port"
			default:     8080
			min:         1
			max:         65535
		}
		TRACE_SAMPLE_RATIO: {
			type:        "float"
			description: "Fraction of requests traced"
			default:     0.1
			min:         0
			max:         1
		}
	}
	files: {
		"serving-tls": {
			type:        "tls"
			description: "Certificate the API serves HTTPS with"
			required:    true
			secret:      true
			path:        "/etc/orders/tls"
			reload:      "watch"
			dnsNames: ["orders.internal"]
			minRemaining: "720h"
		}
		"tax-rates": {
			type:        "config"
			format:      "yaml"
			description: "Tax rates by country, loaded at boot"
			required:    true
			path:        "/etc/orders/tax/rates.yaml"
			schema: {
				type: "object"
				required: ["default", "countries"]
				additionalProperties: false
				properties: {
					default: {
						type:        "number"
						description: "Rate used when a country is not listed"
						minimum:     0
						maximum:     1
					}
					countries: {
						type:        "object"
						description: "Rates by ISO 3166-1 alpha-2 country code"
						additionalProperties: {
							type: "number"
						}
					}
				}
			}
		}
	}
}
