package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"time"

	"cuelang.org/go/cue"
	"cuelang.org/go/encoding/yaml"

	"github.com/docuconf/docuconf-go/cmd/docuconf/internal/platform"
)

// runConformance expands the language-neutral cases in conformance/load
// into conformance/cases.json, the file every SDK's conformance runner
// reads (SPEC §12). With -check it fails if cases.json is out of date.
func runConformance(args []string, stdout, stderr io.Writer) error {
	fs := flag.NewFlagSet("conformance", flag.ContinueOnError)
	fs.SetOutput(stderr)
	dir := fs.String("dir", "conformance", "the conformance directory")
	check := fs.Bool("check", false, "fail if cases.json is out of date instead of writing it")
	if err := fs.Parse(args); err != nil {
		return err
	}
	p, err := platform.New()
	if err != nil {
		return err
	}
	out, err := generateCases(p, filepath.Join(*dir, "load"))
	if err != nil {
		return err
	}
	target := filepath.Join(*dir, "cases.json")
	if *check {
		old, err := os.ReadFile(target)
		if err != nil {
			return err
		}
		if !bytes.Equal(old, out) {
			return fmt.Errorf("%s is out of date; run docuconf conformance -dir %s", target, *dir)
		}
		fmt.Fprintf(stdout, "%s is up to date\n", target)
		return nil
	}
	if err := os.WriteFile(target, out, 0o644); err != nil {
		return err
	}
	fmt.Fprintf(stdout, "wrote %s\n", target)
	return nil
}

type sourceFile struct {
	Description string                    `json:"description"`
	Vars        map[string]map[string]any `json:"vars"`
	Cases       []sourceCase              `json:"cases"`
}

type sourceCase struct {
	Name     string              `json:"name"`
	Requires []string            `json:"requires"`
	Only     map[string][]string `json:"only"`
	Values   map[string]any      `json:"values"`
	Env      map[string]any      `json:"env"`
	Expect   map[string]any      `json:"expect"`
	Errors   []caseError         `json:"errors"`
}

type caseError struct {
	Var  string `json:"var"`
	Code string `json:"code"`
}

type expandedCase struct {
	ID       string            `json:"id"`
	Source   string            `json:"source"`
	Requires []string          `json:"requires"`
	Contract json.RawMessage   `json:"contract"`
	Env      map[string]string `json:"env"`
	Expect   map[string]any    `json:"expect,omitempty"`
	Errors   []caseError       `json:"errors,omitempty"`
}

var (
	listEncodings     = []string{"csv", "json", "indexed"}
	durationEncodings = []string{"go", "iso8601", "seconds", "timespan"}
	codes             = []string{"missing_required", "invalid_type", "out_of_range", "pattern_mismatch", "not_in_enum", "invalid_scheme", "too_few_items", "too_many_items", "schema_mismatch"}
)

func generateCases(p *platform.Platform, loadDir string) ([]byte, error) {
	files, err := filepath.Glob(filepath.Join(loadDir, "*.yaml"))
	if err != nil {
		return nil, err
	}
	if len(files) == 0 {
		return nil, fmt.Errorf("no cases in %s", loadDir)
	}
	slices.Sort(files)
	var all []expandedCase
	for _, f := range files {
		cases, err := expandFile(p, f)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", filepath.Base(f), err)
		}
		all = append(all, cases...)
	}
	doc := map[string]any{
		"comment": "Generated by docuconf conformance from conformance/load. DO NOT EDIT.",
		"version": 1,
		"cases":   all,
	}
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(doc); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// decodeNumbers decodes JSON keeping numbers exact.
func decodeNumbers(data []byte, v any) error {
	d := json.NewDecoder(bytes.NewReader(data))
	d.UseNumber()
	return d.Decode(v)
}

func expandFile(p *platform.Platform, file string) ([]expandedCase, error) {
	src, err := os.ReadFile(file)
	if err != nil {
		return nil, err
	}
	f, err := yaml.Extract(file, src)
	if err != nil {
		return nil, err
	}
	v, err := p.CompileFile(f)
	if err != nil {
		return nil, err
	}
	raw, err := v.MarshalJSON()
	if err != nil {
		return nil, err
	}
	var sf sourceFile
	if err := decodeNumbers(raw, &sf); err != nil {
		return nil, err
	}
	stem := strings.TrimSuffix(filepath.Base(file), ".yaml")
	seen := map[string]bool{}
	var out []expandedCase
	for _, sc := range sf.Cases {
		if sc.Name == "" || seen[sc.Name] {
			return nil, fmt.Errorf("case names must be present and unique: %q", sc.Name)
		}
		seen[sc.Name] = true
		cs, err := expandCase(p, stem, sf, sc)
		if err != nil {
			return nil, fmt.Errorf("case %q: %w", sc.Name, err)
		}
		out = append(out, cs...)
	}
	return out, nil
}

func expandCase(p *platform.Platform, stem string, sf sourceFile, sc sourceCase) ([]expandedCase, error) {
	if (sc.Values == nil) == (sc.Env == nil) {
		return nil, errors.New("give exactly one of values and env")
	}
	if sc.Values != nil && (sc.Expect != nil || sc.Errors != nil) {
		return nil, errors.New("a values case is always valid, and its expected result is derived from the values")
	}
	if sc.Env != nil && (sc.Expect == nil) == (sc.Errors == nil) {
		return nil, errors.New("an env case gives exactly one of expect and errors")
	}
	for _, e := range sc.Errors {
		if sf.Vars[e.Var] == nil {
			return nil, fmt.Errorf("error for undeclared variable %s", e.Var)
		}
		if !slices.Contains(codes, e.Code) {
			return nil, fmt.Errorf("unknown error code %q", e.Code)
		}
	}
	for n := range sc.Expect {
		if sf.Vars[n] == nil {
			return nil, fmt.Errorf("expect names undeclared variable %s", n)
		}
	}

	// A values case runs once per encoding of each list and duration it
	// sets whose encoding the contract leaves open.
	type dim struct {
		key, typ string
		encs     []string
		vars     []string
	}
	dims := []*dim{{key: "list", typ: "list", encs: listEncodings}, {key: "duration", typ: "duration", encs: durationEncodings}}
	for _, d := range dims {
		if only, ok := sc.Only[d.key]; ok {
			d.encs = only
		}
		for n := range sc.Values {
			if v := sf.Vars[n]; v != nil && v["type"] == d.typ && v["encoding"] == nil {
				d.vars = append(d.vars, n)
			}
		}
		if len(d.vars) == 0 {
			d.encs = []string{""}
		}
	}

	var out []expandedCase
	for _, le := range dims[0].encs {
		for _, de := range dims[1].encs {
			vars := map[string]map[string]any{}
			for n, v := range sf.Vars {
				c := map[string]any{}
				for k, x := range v {
					c[k] = x
				}
				vars[n] = c
			}
			var label []string
			if le != "" {
				for _, n := range dims[0].vars {
					vars[n]["encoding"] = le
				}
				label = append(label, "list="+le)
			}
			if de != "" {
				for _, n := range dims[1].vars {
					vars[n]["encoding"] = de
				}
				label = append(label, "duration="+de)
			}
			ec, err := expandVariant(p, stem, sc, vars)
			if err != nil {
				return nil, fmt.Errorf("%s: %w", strings.Join(label, " "), err)
			}
			if len(label) > 0 {
				ec.ID += " [" + strings.Join(label, " ") + "]"
			}
			out = append(out, ec)
		}
	}
	return out, nil
}

var nonLabel = regexp.MustCompile(`[^a-z0-9-]+`)

func expandVariant(p *platform.Platform, stem string, sc sourceCase, vars map[string]map[string]any) (expandedCase, error) {
	doc := map[string]any{
		"apiVersion": "docuconf.dev/v1alpha1",
		"kind":       "ConfigContract",
		"metadata": map[string]any{
			"name":      "conformance-" + nonLabel.ReplaceAllString(strings.ToLower(stem), "-"),
			"generator": map[string]any{"language": "go", "sdk": "docuconf-conformance", "version": "1"},
		},
		"vars": vars,
	}
	data, err := json.Marshal(doc)
	if err != nil {
		return expandedCase{}, err
	}
	src := "package input\n\nimport \"docuconf.dev/contract\"\n\nc: contract.#Contract & " + string(data) + "\n"
	c, err := p.ParseContract(stem+".cue", []byte(src))
	if err != nil {
		return expandedCase{}, err
	}
	contractJSON, err := c.Value.MarshalJSON()
	if err != nil {
		return expandedCase{}, err
	}
	var contract struct {
		Vars map[string]map[string]any `json:"vars"`
	}
	if err := decodeNumbers(contractJSON, &contract); err != nil {
		return expandedCase{}, err
	}
	ec := expandedCase{
		ID:       stem + "/" + sc.Name,
		Source:   "load/" + stem + ".yaml",
		Requires: sc.Requires,
		Contract: contractJSON,
		Env:      map[string]string{},
		Errors:   sc.Errors,
	}
	if ec.Requires == nil {
		ec.Requires = []string{}
	}

	given := sc.Expect
	if sc.Values != nil {
		vdata, err := json.Marshal(sc.Values)
		if err != nil {
			return ec, err
		}
		values, err := p.CompileJSON("values.json", vdata)
		if err != nil {
			return ec, err
		}
		empty, _ := p.CompileJSON("empty.json", []byte("{}"))
		problems, err := p.Validate(c, values, empty, empty, cue.Value{})
		if err != nil {
			return ec, err
		}
		if len(problems) > 0 {
			return ec, fmt.Errorf("the platform rejects the values:\n  %s", strings.Join(problems, "\n  "))
		}
		env, err := p.RenderEnv(c, values)
		if err != nil {
			return ec, err
		}
		for _, e := range env {
			if e.Value == nil {
				return ec, fmt.Errorf("%s: values cases cannot use references", e.Name)
			}
			// Kubernetes reduces $$ to $; the renderer doubled every $.
			ec.Env[e.Name] = strings.ReplaceAll(*e.Value, "$$", "$")
		}
		given = sc.Values
	} else {
		for k, x := range sc.Env {
			s, ok := x.(string)
			if !ok {
				return ec, fmt.Errorf("env %s: env values are strings; quote %v", k, x)
			}
			ec.Env[k] = s
		}
	}

	if sc.Errors == nil {
		ec.Expect = map[string]any{}
		for n, v := range contract.Vars {
			x, ok := given[n]
			if !ok {
				x, ok = v["default"]
			}
			if !ok {
				ec.Expect[n] = nil
				continue
			}
			if v["type"] == "duration" {
				d, err := time.ParseDuration(x.(string))
				if err != nil {
					return ec, fmt.Errorf("%s: %w", n, err)
				}
				x = canonicalDuration(d)
			}
			ec.Expect[n] = x
		}
	}
	return ec, nil
}

// canonicalDuration writes d as SPEC §11.2 item 3 requires: units h, m, s,
// ms, us, ns, each at most once, zero units omitted, and 0s for zero.
func canonicalDuration(d time.Duration) string {
	if d == 0 {
		return "0s"
	}
	var b strings.Builder
	if d < 0 {
		b.WriteByte('-')
		d = -d
	}
	for _, u := range []struct {
		name string
		size time.Duration
	}{{"h", time.Hour}, {"m", time.Minute}, {"s", time.Second}, {"ms", time.Millisecond}, {"us", time.Microsecond}, {"ns", time.Nanosecond}} {
		if n := d / u.size; n > 0 {
			fmt.Fprintf(&b, "%d%s", n, u.name)
			d -= n * u.size
		}
	}
	return b.String()
}
