package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestDocsGolden checks the committed docs of every example contract and
// of the orders example against what docuconf docs writes today, for the
// contract and for the committed docs model as input.
func TestDocsGolden(t *testing.T) {
	contracts, _ := filepath.Glob(examples + "/*_contract.cue")
	if len(contracts) == 0 {
		t.Fatal("no example contracts")
	}
	type golden struct{ contract, dir string }
	var all []golden
	for _, c := range contracts {
		all = append(all, golden{c, "../../spec/cue/testdata/docs/" + strings.TrimSuffix(filepath.Base(c), "_contract.cue")})
	}
	all = append(all, golden{"../../examples/orders/contract.cue", "../../examples/orders"})
	for _, g := range all {
		for format, file := range map[string]string{"model": "docs.json", "markdown": "CONFIG.md", "agents": "CONFIG.agents.md"} {
			want := filepath.Join(g.dir, file)
			if _, errOut, code := docuconf(t, "docs", g.contract, "--format", format, "--check", want); code != 0 {
				t.Errorf("%s is out of date (run spec/cue/testdata/docs/generate.sh, or see the README for the orders example):\n%s", want, errOut)
			}
			if format == "model" {
				continue
			}
			if _, errOut, code := docuconf(t, "docs", filepath.Join(g.dir, "docs.json"), "--format", format, "--check", want); code != 0 {
				t.Errorf("rendering %s/docs.json differs from %s:\n%s", g.dir, want, errOut)
			}
		}
	}
}

func TestDocsCommand(t *testing.T) {
	// Markdown is the default; flags may follow the contract.
	md, errOut, code := docuconf(t, "docs", billing)
	if code != 0 || !strings.HasPrefix(md, "<!-- Generated by docuconf. Do not edit. -->\n\n# billing-api configuration\n") {
		t.Fatalf("exit %d, stderr %s, stdout:\n%s", code, errOut, md)
	}
	model, _, code := docuconf(t, "docs", "--format", "model", billing)
	if code != 0 || !strings.Contains(model, `"apiVersion": "docs.docuconf.dev/v1alpha1"`) {
		t.Fatalf("model: exit %d\n%s", code, model)
	}
	agents, _, code := docuconf(t, "docs", "-contract", billing, "--format", "agents")
	if code != 0 || !strings.Contains(agents, "## Hard rules") {
		t.Fatalf("agents: exit %d\n%s", code, agents)
	}

	// The model is the intermediary: rendering it gives the same docs.
	modelFile := write(t, "docs.json", model)
	fromModel, errOut, code := docuconf(t, "docs", modelFile)
	if code != 0 || fromModel != md {
		t.Fatalf("rendering the model: exit %d, stderr %s, same output %v", code, errOut, fromModel == md)
	}

	// A contract as JSON (here the one docuconf helm writes) gives the
	// same docs as the CUE it came from.
	fromJSON, errOut, code := docuconf(t, "docs", "../../examples/helm/gateway/files/docuconf/contract.json", "--format", "model")
	fromCUE, _, _ := docuconf(t, "docs", gateway, "--format", "model")
	if code != 0 || fromJSON != fromCUE {
		t.Errorf("JSON contract: exit %d, stderr %s, same output %v", code, errOut, fromJSON == fromCUE)
	}

	// -o writes; --check passes on the same bytes and fails on others.
	out := filepath.Join(t.TempDir(), "CONFIG.md")
	if _, errOut, code := docuconf(t, "docs", billing, "-o", out); code != 0 {
		t.Fatalf("-o: exit %d: %s", code, errOut)
	}
	if _, errOut, code := docuconf(t, "docs", billing, "--check", out); code != 0 {
		t.Fatalf("--check of fresh docs: exit %d: %s", code, errOut)
	}
	stale := strings.Replace(read(t, out), "HTTP listen port", "HTTP port", 1)
	if err := os.WriteFile(out, []byte(stale), 0o644); err != nil {
		t.Fatal(err)
	}
	_, errOut, code = docuconf(t, "docs", billing, "--check", out)
	if code != 1 || !strings.Contains(errOut, "is out of date (1 line added, 1 line removed); regenerate it with: docuconf docs") ||
		!strings.Contains(errOut, "-- [`PORT`](#port): HTTP port") || !strings.Contains(errOut, "+- [`PORT`](#port): HTTP listen port") {
		t.Fatalf("--check of stale docs: exit %d:\n%s", code, errOut)
	}
}

func TestDocsErrors(t *testing.T) {
	for _, c := range []struct {
		args []string
		want string
	}{
		{[]string{"docs"}, "no contract given"},
		{[]string{"docs", billing, "--format", "html"}, `unknown --format "html"`},
		{[]string{"docs", billing, gateway}, "one contract at a time"},
		{[]string{"docs", billing, "-o", "a", "--check", "b"}, "-o and --check cannot be used together"},
		{[]string{"docs", write(t, "docs.json", `{"apiVersion": "docs.docuconf.dev/v1alpha1", "kind": "ConfigDocs"}`)}, "is not a valid docs model"},
		{[]string{"docs", write(t, "bad.cue", "package x\nx: 1\n")}, "holds no ConfigContract"},
	} {
		_, errOut, code := docuconf(t, c.args...)
		if code != 2 || !strings.Contains(errOut, c.want) {
			t.Errorf("%v: exit %d, want 2 and %q in:\n%s", c.args, code, c.want, errOut)
		}
	}
}
