// This file is shared by cmd/docuconf and cmd/docuconf-export, which must
// keep identical copies (export_sync_test.go in the SDK checks it). It
// depends only on the standard library.

package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"text/template"
)

// sdkModule is the Go SDK whose Export the generated program calls.
const sdkModule = "github.com/docuconf/docuconf-go"

// errStale means export -check found the contract out of date; the diff
// has been printed already.
var errStale = errors.New("contract is out of date")

// generatorVersion matches the value of metadata.generator.version, the
// SDK version, which every release bumps. -check ignores it, so that a
// release does not make every committed contract stale.
var generatorVersion = regexp.MustCompile(`(generator:\s*\{[^{}]*?\bversion:\s*)"[^"]*"`)

// sameContract reports whether two contracts are equal apart from
// metadata.generator.version.
func sameContract(a, b []byte) bool {
	norm := func(c []byte) []byte { return generatorVersion.ReplaceAll(c, []byte(`${1}""`)) }
	return bytes.Equal(norm(a), norm(b))
}

var exportMain = template.Must(template.New("main").Parse(`// Code generated by docuconf export. DO NOT EDIT.
package main

import (
	"fmt"
	"os"

	docuconf {{printf "%q" .SDK}}
	target {{printf "%q" .ImportPath}}
)

func main() {
	out, err := docuconf.Export[target.{{.Type}}](docuconf.Meta{
		Name:       {{printf "%q" .Name}},
		AppVersion: {{printf "%q" .AppVersion}},
		Package:    {{printf "%q" .Package}},
		SourceDir:  {{printf "%q" .Dir}},
		Prefix:     {{printf "%q" .Prefix}},
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	os.Stdout.Write(out)
}
`))

const exportUsage = `Usage: docuconf export [flags]

Writes the contract for a Go configuration struct. It compiles and runs a
small program inside your module (with go run), so it needs the Go
toolchain and your module's dependencies, but no environment values.

Flags:
`

// runExport exports a Go configuration struct. Export needs the struct's
// real type (for reflection) and its source (for doc comments), so it
// writes a small program that calls docuconf.Export and runs it with
// go run inside the app's own module, using the SDK version the app uses.
// The program lives in a temporary directory under the module root, so it
// may import internal packages.
func runExport(args []string, stdout, stderr io.Writer) error {
	fs := flag.NewFlagSet("export", flag.ContinueOnError)
	fs.SetOutput(stderr)
	fs.Usage = func() {
		fmt.Fprint(fs.Output(), exportUsage)
		fs.PrintDefaults()
	}
	var (
		pkg        = fs.String("pkg", ".", "Go package holding the configuration struct, such as ./internal/config")
		typ        = fs.String("type", "Config", "name of the configuration struct type")
		name       = fs.String("name", "", "service name, a DNS label (default: the last element of the module path)")
		appVersion = fs.String("app-version", "", "version or git SHA recorded in the contract")
		cuePkg     = fs.String("package", "", "CUE package clause (default: the name with _ for -)")
		prefix     = fs.String("prefix", "", "env.Options.Prefix the app parses with (default: from the struct's DocuconfOptions method)")
		dir        = fs.String("C", ".", "run in this directory (inside the app's module)")
		out        = fs.String("o", "", "write the contract here instead of stdout")
		check      = fs.String("check", "", "compare with this contract file instead of writing; exit 1 with a diff if it is out of date (metadata.generator.version is ignored)")
	)
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() > 0 {
		return fmt.Errorf("unexpected argument %q; flags go before arguments, and export takes none", fs.Arg(0))
	}
	if *out != "" && *check != "" {
		return errors.New("-o and -check cannot be used together")
	}
	if !isIdent(*typ) {
		return fmt.Errorf("-type %q is not a Go identifier", *typ)
	}

	var info struct {
		ImportPath string
		Name       string
		Dir        string
		GoFiles    []string
		Module     *struct {
			Path string
			Dir  string
			Main bool
		}
	}
	list := exec.Command("go", "list", "-json=ImportPath,Name,Dir,GoFiles,Module", *pkg)
	list.Dir = *dir
	var listErr bytes.Buffer
	list.Stderr = &listErr
	b, err := list.Output()
	if err != nil {
		return fmt.Errorf("cannot find package %s: %s", *pkg, strings.TrimSpace(listErr.String()))
	}
	if err := json.Unmarshal(b, &info); err != nil {
		return err
	}
	if info.Name == "main" {
		return fmt.Errorf("%s is package main, which cannot be imported; move the configuration struct to its own package, or call docuconf.Export from your program", info.ImportPath)
	}
	if types := packageTypes(info.Dir, info.GoFiles); !slices.Contains(types, *typ) {
		return fmt.Errorf("no type %s in %s (types: %s); pass the struct's name with -type", *typ, info.ImportPath, strings.Join(types, ", "))
	}
	if *name == "" {
		modPath := ""
		if info.Module != nil {
			modPath = info.Module.Path
		}
		*name = nameFromModule(modPath)
		if *name == "" {
			return fmt.Errorf("-name is required: cannot derive a service name (a DNS label) from module path %q", modPath)
		}
	}

	root, err := moduleRoot(*dir, info.Module)
	if err != nil {
		return err
	}
	tmp, err := os.MkdirTemp(root, "_docuconf_export_")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmp)
	var src bytes.Buffer
	err = exportMain.Execute(&src, map[string]string{
		"SDK": sdkModule, "ImportPath": info.ImportPath, "Type": *typ, "Name": *name,
		"AppVersion": *appVersion, "Package": *cuePkg, "Dir": info.Dir, "Prefix": *prefix,
	})
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(tmp, "main.go"), src.Bytes(), 0o644); err != nil {
		return err
	}

	var contract, errOut bytes.Buffer
	run := exec.Command("go", "run", ".")
	run.Dir = tmp
	run.Stdout = &contract
	run.Stderr = &errOut
	if err := run.Run(); err != nil {
		msg := cleanRunOutput(errOut.String())
		if strings.Contains(msg, sdkModule) && strings.Contains(msg, "no required module provides") {
			msg += "\nhint: add the SDK to the app's module with: go get " + sdkModule
		}
		return errors.New(msg)
	}

	switch {
	case *check != "":
		have, err := os.ReadFile(*check)
		if err != nil {
			return err
		}
		if sameContract(have, contract.Bytes()) {
			return nil
		}
		fmt.Fprintf(stderr, "%s is out of date; regenerate it with docuconf export -o %s\n", *check, *check)
		writeDiff(stderr, *check, "exported now", string(have), contract.String())
		return errStale
	case *out == "":
		_, err = stdout.Write(contract.Bytes())
		return err
	}
	return os.WriteFile(*out, contract.Bytes(), 0o644)
}

// moduleRoot is the directory the generated program goes under: the root
// of the module holding the package, so that it may import the package
// even under internal/, or else the main module's root.
func moduleRoot(dir string, mod *struct {
	Path string
	Dir  string
	Main bool
}) (string, error) {
	if mod != nil && mod.Main && mod.Dir != "" {
		return mod.Dir, nil
	}
	cmd := exec.Command("go", "env", "GOMOD")
	cmd.Dir = dir
	b, err := cmd.Output()
	gomod := strings.TrimSpace(string(b))
	if err != nil || gomod == "" || gomod == os.DevNull {
		return "", errors.New("run docuconf export inside the app's Go module (use -C to point at it)")
	}
	return filepath.Dir(gomod), nil
}

// packageTypes returns the names of the types declared at the top level
// of a package's Go files, sorted.
func packageTypes(dir string, files []string) []string {
	var names []string
	fset := token.NewFileSet()
	for _, f := range files {
		file, err := parser.ParseFile(fset, filepath.Join(dir, f), nil, parser.SkipObjectResolution)
		if err != nil {
			continue
		}
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				names = append(names, spec.(*ast.TypeSpec).Name.Name)
			}
		}
	}
	slices.Sort(names)
	return names
}

var (
	majorSuffixRe = regexp.MustCompile(`^v[0-9]+$`)
	nonLabelRe    = regexp.MustCompile(`[^a-z0-9-]+`)
	dnsLabelRe    = regexp.MustCompile(`^[a-z0-9]([-a-z0-9]{0,61}[a-z0-9])?$`)
)

// nameFromModule derives a service name from a module path: its last
// element (skipping a /vN suffix), lowercased, with anything outside
// [a-z0-9-] replaced by a dash. It returns "" if that is not a DNS label.
func nameFromModule(modPath string) string {
	elems := strings.Split(modPath, "/")
	last := elems[len(elems)-1]
	if majorSuffixRe.MatchString(last) && len(elems) > 1 {
		last = elems[len(elems)-2]
	}
	name := strings.Trim(nonLabelRe.ReplaceAllString(strings.ToLower(last), "-"), "-")
	if !dnsLabelRe.MatchString(name) {
		return ""
	}
	return name
}

var exitStatusRe = regexp.MustCompile(`(?m)^exit status [0-9]+\n?`)

// cleanRunOutput turns go run's stderr into an error message: without the
// "exit status 1" go run adds, and without the SDK's "docuconf: " prefix,
// which the command adds itself.
func cleanRunOutput(s string) string {
	s = strings.TrimSpace(exitStatusRe.ReplaceAllString(s, ""))
	return strings.TrimPrefix(s, "docuconf: ")
}

// writeDiff prints a line diff of two texts in unified diff style: the
// changed lines with two lines of context, without line numbers. label
// says where b comes from, such as "exported now".
func writeDiff(w io.Writer, name, label, a, b string) {
	al, bl := strings.SplitAfter(a, "\n"), strings.SplitAfter(b, "\n")
	// Longest common subsequence lengths, from the end.
	lcs := make([][]int, len(al)+1)
	for i := range lcs {
		lcs[i] = make([]int, len(bl)+1)
	}
	for i := len(al) - 1; i >= 0; i-- {
		for j := len(bl) - 1; j >= 0; j-- {
			if al[i] == bl[j] {
				lcs[i][j] = lcs[i+1][j+1] + 1
			} else {
				lcs[i][j] = max(lcs[i+1][j], lcs[i][j+1])
			}
		}
	}
	type op struct{ prefix, text string }
	var ops []op
	i, j := 0, 0
	for i < len(al) || j < len(bl) {
		switch {
		case i < len(al) && j < len(bl) && al[i] == bl[j]:
			ops = append(ops, op{" ", al[i]})
			i, j = i+1, j+1
		case j < len(bl) && (i == len(al) || lcs[i][j+1] >= lcs[i+1][j]):
			ops = append(ops, op{"+", bl[j]})
			j++
		default:
			ops = append(ops, op{"-", al[i]})
			i++
		}
	}
	const context = 2
	show := make([]bool, len(ops))
	for k, o := range ops {
		if o.prefix != " " {
			for c := max(0, k-context); c <= min(len(ops)-1, k+context); c++ {
				show[c] = true
			}
		}
	}
	fmt.Fprintf(w, "--- %s\n+++ %s (%s)\n", name, path.Base(name), label)
	gap := true
	for k, o := range ops {
		if !show[k] {
			gap = true
			continue
		}
		if gap {
			fmt.Fprintln(w, "@@")
			gap = false
		}
		if o.text != "" {
			fmt.Fprint(w, o.prefix+strings.TrimSuffix(o.text, "\n")+"\n")
		}
	}
}

func isIdent(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		if !(r == '_' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || i > 0 && r >= '0' && r <= '9') {
			return false
		}
	}
	return true
}
