package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"text/template"
)

// sdkModule is the Go SDK whose Export the generated program calls.
const sdkModule = "github.com/docuconf/docuconf-go"

var exportMain = template.Must(template.New("main").Parse(`// Code generated by docuconf export. DO NOT EDIT.
package main

import (
	"fmt"
	"os"

	docuconf {{printf "%q" .SDK}}
	target {{printf "%q" .ImportPath}}
)

func main() {
	out, err := docuconf.Export[target.{{.Type}}](docuconf.Meta{
		Name:       {{printf "%q" .Name}},
		AppVersion: {{printf "%q" .AppVersion}},
		Package:    {{printf "%q" .Package}},
		SourceDir:  {{printf "%q" .Dir}},
		Prefix:     {{printf "%q" .Prefix}},
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	os.Stdout.Write(out)
}
`))

// runExport exports a Go configuration struct. Export needs the struct's
// real type (for reflection) and its source (for doc comments), so it
// writes a small program that calls docuconf.Export and runs it with
// go run inside the app's own module, using the SDK version the app uses.
func runExport(args []string, stdout, stderr io.Writer) error {
	fs := flag.NewFlagSet("export", flag.ContinueOnError)
	fs.SetOutput(stderr)
	var (
		pkg        = fs.String("pkg", ".", "Go package holding the configuration struct")
		typ        = fs.String("type", "Config", "name of the configuration struct type")
		name       = fs.String("name", "", "service name, a DNS label (required)")
		appVersion = fs.String("app-version", "", "version or git SHA recorded in the contract")
		cuePkg     = fs.String("package", "", "CUE package clause (default: the name with _ for -)")
		prefix     = fs.String("prefix", "", "env.Options.Prefix the app parses with")
		dir        = fs.String("C", ".", "run in this directory (inside the app's module)")
		out        = fs.String("o", "", "write the contract here instead of stdout")
	)
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *name == "" {
		return errors.New("-name is required")
	}
	if !isIdent(*typ) {
		return fmt.Errorf("-type %q is not a Go identifier", *typ)
	}

	var info struct {
		ImportPath string
		Name       string
		Dir        string
	}
	list := exec.Command("go", "list", "-json=ImportPath,Name,Dir", *pkg)
	list.Dir = *dir
	list.Stderr = stderr
	b, err := list.Output()
	if err != nil {
		return fmt.Errorf("go list %s: %w", *pkg, err)
	}
	if err := json.Unmarshal(b, &info); err != nil {
		return err
	}
	if info.Name == "main" {
		return fmt.Errorf("%s is package main, which cannot be imported; move the configuration struct to its own package, or call docuconf.Export from your program", info.ImportPath)
	}

	tmp, err := os.MkdirTemp("", "docuconf-export-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmp)
	var src bytes.Buffer
	err = exportMain.Execute(&src, map[string]string{
		"SDK": sdkModule, "ImportPath": info.ImportPath, "Type": *typ, "Name": *name,
		"AppVersion": *appVersion, "Package": *cuePkg, "Dir": info.Dir, "Prefix": *prefix,
	})
	if err != nil {
		return err
	}
	mainFile := filepath.Join(tmp, "main.go")
	if err := os.WriteFile(mainFile, src.Bytes(), 0o644); err != nil {
		return err
	}

	var contract, errOut bytes.Buffer
	run := exec.Command("go", "run", mainFile)
	run.Dir = *dir
	run.Stdout = &contract
	run.Stderr = &errOut
	if err := run.Run(); err != nil {
		msg := errOut.String()
		if bytes.Contains(errOut.Bytes(), []byte(sdkModule)) && bytes.Contains(errOut.Bytes(), []byte("no required module provides")) {
			msg += "hint: add the SDK to the app's module with: go get " + sdkModule + "\n"
		}
		return fmt.Errorf("%s", msg)
	}
	if *out == "" {
		_, err = stdout.Write(contract.Bytes())
		return err
	}
	return os.WriteFile(*out, contract.Bytes(), 0o644)
}

func isIdent(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		if !(r == '_' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || i > 0 && r >= '0' && r <= '9') {
			return false
		}
	}
	return true
}
