// Code generated by docuconf. DO NOT EDIT.
package orders_batch

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "orders-batch"
		generator: {
			language: "cobol"
			sdk:      "docuconf-cobol"
			version:  "0.1.0"
		}
	}
	vars: {
		ALLOWED_ORIGINS: {
			type:        "list"
			description: "Allowed origins"
			default: ["http://localhost:3000"]
			encoding: "indexed"
			items:    "string"
			minItems: 1
			maxItems: 4
		}
		DATABASE_URL: {
			type:        "url"
			description: "Orders database"
			required:    true
			secret:      true
			schemes: ["postgres"]
		}
		LIMITS: {
			type:        "json"
			description: "Rate limits"
			schema: {
				properties: {
					perMinute: {
						minimum: 1
						type:    "integer"
					}
				}
				type: "object"
			}
		}
		LOG_LEVEL: {
			type:        "enum"
			description: "Log verbosity"
			default:     "info"
			values: ["debug", "info"]
		}
		PORT: {
			type:        "int"
			description: "Metrics port"
			default:     8080
			min:         1
			max:         65535
		}
		REQUEST_TIMEOUT: {
			type:        "duration"
			description: "Request timeout"
			default:     "30s"
			min:         "1s"
			max:         "5m"
			encoding:    "seconds"
		}
	}
	files: {
		name: {
			type:        "binary"
			description: "An input called name"
			path:        "/srv/blobs/name.bin"
		}
		orders: {
			type:        "text"
			description: "Orders to process"
			required:    true
			path:        "/data/orders.txt"
			pathEnv:     "ORDERS_FILE"
			maxSize:     1048576
		}
	}
}
