// Code generated by docuconf. DO NOT EDIT.
package gateway

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "gateway"
		generator: {
			language: "go"
			sdk:      "docuconf-go"
			version:  "0.1.0"
		}
	}
	vars: {
		ALLOWED_ORIGINS: {
			type:        "list"
			description: "CORS origins allowed to call the API"
			required:    true
			examples: ["https://app.example.com"]
			items:     "string"
			encoding:  "csv"
			separator: ","
			minItems:  1
		}
		CACHE_SIZE: {
			type:        "int"
			description: "Maximum cached entries"
			default:     1000
			min:         0
			max:         4294967295
		}
		CACHE_TTL: {
			type:        "duration"
			description: "Cache entry lifetime"
			default:     "5m"
			encoding:    "go"
		}
		DATABASE_URL: {
			type:        "url"
			description: "Primary Postgres connection string"
			required:    true
			secret:      true
			schemes: ["postgres", "postgresql"]
		}
		DEBUG: {
			type:        "bool"
			description: "Serve the debug endpoints"
			default:     false
		}
		EXTRA_PORTS: {
			type:        "list"
			description: "Extra ports to listen on"
			items:       "int"
			encoding:    "csv"
			separator:   ";"
			maxItems:    4
			itemMin:     1
			itemMax:     65535
		}
		GOMEMLIMIT: {
			type:        "int"
			description: "Go runtime soft memory limit, in bytes"
			min:         1
		}
		LOG_LEVEL: {
			type:        "enum"
			description: "Minimum log level emitted"
			default:     "info"
			group:       "logging"
			values: ["debug", "info", "warn", "error"]
		}
		PARTNER_KEYSTORE_PASSWORD: {
			type:        "string"
			description: "Password for the partner mTLS keystore"
			required:    true
			secret:      true
		}
		POD_NAMESPACE: {
			type:        "string"
			description: "Namespace the gateway runs in, for metrics labels"
			required:    true
		}
		PORT: {
			type:        "int"
			description: "HTTP listen port"
			default:     8080
			min:         1
			max:         65535
		}
		RATE_LIMITS: {
			type:        "json"
			description: "Default per-client rate limits"
			default: {
				perMinute: 60
			}
			schema: {
				type: "object"
				required: ["perMinute"]
				additionalProperties: false
				properties: {
					perMinute: {
						type:        "integer"
						description: "Requests allowed per minute"
						minimum:     1
					}
					burst: {
						type:        "integer"
						description: "Extra requests allowed in a burst"
						minimum:     0
					}
				}
			}
		}
		REGION: {
			type:        "string"
			description: "Cloud region, such as eu-west-1"
			deprecated: {
				message: "Read from the node's topology labels instead"
			}
			minLength: 4
			maxLength: 32
			pattern:   "^[a-z]{2}-[a-z]+-[0-9]$"
		}
		REQUEST_TIMEOUT: {
			type:        "duration"
			description: "Upstream request timeout"
			details:     "The gateway gives up on an upstream after this long and answers 504. Raise it for slow batch endpoints; keep it below the load balancer's idle timeout.\n\n# Choosing a value\n\nMeasure the upstream's p99 latency first:\n\n\thistogram_quantile(0.99, upstream_seconds_bucket)"
			default:     "30s"
			min:         "1s"
			max:         "5m"
			encoding:    "go"
		}
		STRIPE_API_BASE: {
			type:        "url"
			description: "Stripe API base URL"
			default:     "https://api.stripe.com"
			schemes: ["https"]
		}
		TRACE_SAMPLE_RATIO: {
			type:        "float"
			description: "Fraction of requests traced"
			default:     0.1
			min:         0
			max:         1
		}
		WORKER_COUNT: {
			type:        "int"
			description: "Number of background workers"
			default:     4
			min:         1
			max:         127
		}
	}
	files: {
		geoip: {
			type:        "binary"
			description: "GeoIP database for country-based routing"
			path:        "/data/geoip/GeoLite2-City.mmdb"
			maxSize:     134217728
		}
		license: {
			type:        "text"
			description: "Gateway licence key"
			required:    true
			path:        "/etc/gateway/license/license.key"
			pattern:     "^[A-Z0-9]{5}(-[A-Z0-9]{5}){3}\\n?$"
		}
		"partner-keystore": {
			type:        "keystore"
			format:      "pkcs12"
			description: "Client certificate for mTLS to the partner API"
			secret:      true
			path:        "/etc/gateway/partner/keystore.p12"
			passwordVar: "PARTNER_KEYSTORE_PASSWORD"
		}
		routes: {
			type:        "config"
			format:      "yaml"
			description: "Routing table: path prefixes and their upstreams"
			required:    true
			path:        "/etc/gateway/routes/routes.yaml"
			pathEnv:     "ROUTES_FILE"
			reload:      "watch"
			maxSize:     65536
			schema: {
				type: "object"
				required: ["routes"]
				additionalProperties: false
				properties: {
					routes: {
						type:        "array"
						description: "Routes in match order"
						items: {
							type: "object"
							required: ["match", "upstream"]
							additionalProperties: false
							properties: {
								match: {
									type:        "string"
									description: "Path prefix the route matches"
									pattern:     "^/"
								}
								upstream: {
									type:        "string"
									description: "Upstream base URL"
									pattern:     "^https?://"
								}
								timeout: {
									type:        "string"
									description: "Per-request timeout, such as 5s"
									pattern:     "^([0-9]+(ms|s|m))+$"
								}
							}
						}
						minItems: 1
					}
				}
			}
		}
		"serving-tls": {
			type:        "tls"
			description: "Certificate the gateway serves HTTPS with"
			required:    true
			secret:      true
			path:        "/etc/gateway/tls"
			reload:      "watch"
			dnsNames: ["gateway.internal", "api.example.com"]
			keyAlgorithms: ["ECDSA", "RSA"]
			minRemaining: "720h"
		}
		"upstream-ca": {
			type:        "caBundle"
			description: "Private CAs the gateway trusts for upstream TLS"
			path:        "/etc/gateway/ca/bundle.pem"
			pathEnv:     "SSL_CERT_FILE"
		}
	}
}
